language: python

matrix:
  include:
  - python: "2.7"
    env: VERSION=27
  - python: "3.4"
    env: VERSION=34

env:
  global:
    - ENCRYPTION_LABEL: "57984b21888c"
    - COMMIT_AUTHOR_EMAIL: "iuryalves20@gmail.com"

before_script:
  - sudo apt-get install graphviz
  - pip install -r requirements/develop.txt

script:
  - tox -e py$VERSION

after_success:
  - coveralls
  - travis-sphinx  -n build
  - travis-sphinx deploy
